### ISSUE TITLE
Can this model be applied to Multiple cards.

### ISSUE THREAD

**Issue by ahaemhumright** [daveredrum/SceneTex#3]
Hi, thank u for the wonderful work. I am currently using the server with 2 4090 cards with 24GB memory for each one. I wonder if it is possible and how to optimize the model using both graphic cards.  Thanks.

**Comment by daveredrum** [comment]
Hi @YMX2022, currently we don't support multiple GPUs. But you can change the settings so that the model can be fit into a smaller GPU. Specifically, if you go to `config/template.yaml`, change `latent_size` to 64 should do the trick. If it's still too big, you can replace ControlNet with SD Depth2Image by changing `diffusion_type` to `d2i`.
